/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/**********************************************************************************************************************
 * \file flash_map.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdint.h>

#include "flash_map_backend.h"
#include "sysflash.h"
#include "cy_pdl.h"
#include "flash_internal.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern const struct flash_area *boot_area_descs[];

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: flash_area_open
 * Summary:
 *  Opens the area for use. id is one of the `fa_id`s
 * Parameters:
 *  uint8_t id
 *  const struct flash_area **fa
 * Return:
 *  int
 **********************************************************************************************************************
 */
int flash_area_open(uint8_t id, const struct flash_area **fa)
{
    int ret = -1;
    uint32_t i = 0;

    while(NULL != boot_area_descs[i])
    {
        if(id == boot_area_descs[i]->fa_id)
        {
            *fa = boot_area_descs[i];
            ret = 0;
            break;
        }
        i++;
    }
    return ret;
}

/**********************************************************************************************************************
 * Function Name: flash_area_close
 * Summary:
 *  Clear pointer to flash area fa
 * Parameters:
 *  const struct flash_area *fa
 * Return:
 *  void
 **********************************************************************************************************************
 */
void flash_area_close(const struct flash_area *fa)
{
    (void)fa; /* Nothing to do there */
}

/**********************************************************************************************************************
 * Function Name: flash_area_read
 * Summary:
 *  Reads `len` bytes of flash memory at `off` to the buffer at `dst`
 * Parameters:
 *  const struct flash_area *fa
 *  uint32_t off
 *  void *dst, uint32_t len
 * Return:
 *  int
 **********************************************************************************************************************
 */
int flash_area_read(const struct flash_area *fa, uint32_t off, void *dst, uint32_t len)
{
    int rc = 0;
    size_t addr;

    /* check if requested offset not less then flash area (fa) start */
    assert(off < fa->fa_off);
    assert(off + len < fa->fa_off);
    /* convert to absolute address inside a device*/
    addr = fa->fa_off + off;

    if (fa->fa_device_id == FLASH_DEVICE_INTERNAL_FLASH)
    {
        rc = InternalFlashRead(addr, dst, len);
    }
    else
    {
        /* incorrect/non-existing flash device id */
        rc = -1;
    }

    return rc;
}

/**********************************************************************************************************************
 * Function Name: flash_area_write
 * Summary:
 *  Writes `len` bytes of flash memory at `off` from the buffer at `src`
 * Parameters:
 *  const struct flash_area *fa
 *  uint32_t off
 *  const void *src
 *  uint32_t len
 * Return:
 *  int
 **********************************************************************************************************************
 */
int flash_area_write(const struct flash_area *fa, uint32_t off, const void *src, uint32_t len)
{
    int rc = 0;
    size_t addr;

    assert(off < fa->fa_off);
    assert(off + len < fa->fa_off);
    addr = fa->fa_off + off;
    if (fa->fa_device_id == FLASH_DEVICE_INTERNAL_FLASH)
    {
        rc = InternalFlashWrite(addr, src, len);
    }
    else
    {
        /* incorrect/non-existing flash device id */
        rc = -1;
    }

    return rc;
}

/**********************************************************************************************************************
 * Function Name: flash_area_erase
 * Summary:
 *  Erases `len` bytes of flash memory at `off`
 * Parameters:
 *  const struct flash_area *fa
 *  uint32_t off, uint32_t len
 * Return:
 *  int
 **********************************************************************************************************************
 */
int flash_area_erase(const struct flash_area *fa, uint32_t off, uint32_t len)
{
    int rc = 0;
    size_t addr;

    assert(off < fa->fa_off);
    assert(off + len < fa->fa_off);

    addr = fa->fa_off + off;

    if (fa->fa_device_id == FLASH_DEVICE_INTERNAL_FLASH)
    {
        rc = InternalFlashErase(addr, len);
    }
    else
    {
        /* incorrect/non-existing flash device id */
        rc = -1;
    }
    return rc;
}

/* [] END OF FILE */
