/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * Modifications are Copyright (c) 2019 Arm Limited.
 */

/**********************************************************************************************************************
 * \file bootutil_misc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <assert.h>
#include <string.h>
#include <inttypes.h>
#include <stddef.h>

#include "sysflash.h"
#include "flash_map_backend.h"
#include "bootutil_priv.h"

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: boot_set_pending
 * Summary:
 *  In this implementation, this function sets the flash marker located in Work Flash
 *  to make next boot up use the current inactive bank as the active bank.
 * Parameters:
 *  image             0 = Secondary_Slot_1, 1 = Secondary_Slot_2 (not used)
 *  mode              how the marker should be set to:
 *                      0=make the current inactive bank active
 *                      1=make the marker point to current active bank
 * Return:
 *  int               0 on success; nonzero on failure.
 **********************************************************************************************************************
 */
int
boot_set_pending(int image, int mode)
{
    uint32_t marker[4];
    uint32_t valueA, valueB;
    int ret = -1;

    (void)image;

    /* Enable write operation of WorkFlash */
    Cy_Flashc_WorkWriteEnable();
    if (Cy_Flash_EraseSector(0x14012000) == CY_FLASH_DRV_SUCCESS)
    {
        /* Determine the value to be written according to the mode */
        if (mode == 0)
        {
            valueA = 0xAAAAAAAA;
            valueB = 0xFFFFFFFF;
        }
        else
        {
            valueA = 0xFFFFFFFF;
            valueB = 0xAAAAAAAA;
        }
        marker[0] = ((cy_en_maptype_t)_FLD2VAL(FLASHC_FLASH_CTL_MAIN_MAP,FLASHC_FLASH_CTL) == CY_FLASH_MAPPING_A
                                                                                                ? valueA : valueB);
        marker[1] = marker[2] = marker[3] = 0xFFFFFFFF;

        /* Write the marker value to Work Flash */
        cy_stc_flash_programrow_config_t config =
        {
            .destAddr  =  (const uint32_t *)0x14012000,
            .dataAddr  =  (const uint32_t *)marker,
            .blocking  =  CY_FLASH_PROGRAMROW_BLOCKING,
            .skipBC    =  CY_FLASH_PROGRAMROW_SKIP_BLANK_CHECK,
            .dataSize  =  CY_FLASH_PROGRAMROW_DATA_SIZE_128BIT,
            .dataLoc   =  CY_FLASH_PROGRAMROW_DATA_LOCATION_SRAM,
            .intrMask  =  CY_FLASH_PROGRAMROW_NOT_SET_INTR_MASK,
        };
        if (Cy_Flash_Program_WorkFlash(&config) == CY_FLASH_DRV_SUCCESS)
        {
            ret = 0;
        }
    }

    /* Disable write operation of WorkFlash */
    Cy_Flashc_WorkWriteDisable();

    return ret;
}

/**********************************************************************************************************************
 * Function Name: boot_set_pending
 * Summary:
 *  Marks the image in the primary slot as confirmed.  The system will continue
 *  booting into the image in the primary slot until told to boot from a different slot.
 * Return:
 *  int               0 on success; nonzero on failure.
 **********************************************************************************************************************
 */
int
boot_set_confirmed(void)
{
    return 0;   /* not implemented, always return success */
}

/* [] END OF FILE */
